name: Bug Report
description: Report a bug or unexpected behavior in Conjure
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us understand and fix the issue.

        **Note**: If you're having trouble installing or setting up the extension, please use the "Installation / Setup Issue" template instead.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the steps you took and what went wrong.
      placeholder: |
        1. I opened the side panel on example.com
        2. I asked the AI to create a button component
        3. The component was generated but didn't inject into the page
        4. The console shows an error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: |
        Expected: The component should appear on the page
        Actual: Nothing was injected and an error appeared in the side panel
    validations:
      required: true

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Logs or Screenshots
      description: |
        Please provide any error messages, logs, or screenshots that might help.

        **How to get logs:**
        - Open DevTools on the **page** (F12 → Console tab)
        - Open DevTools on the **extension** (chrome://extensions → Conjure → "Inspect views: service worker")
        - Check the side panel console for agent errors
      placeholder: |
        Paste logs here or drag and drop screenshots.
        Error messages and stack traces are very helpful!
    validations:
      required: false

  - type: textarea
    id: website-url
    attributes:
      label: Website URL
      description: Which website were you on when the bug occurred? (if applicable)
      placeholder: e.g. https://example.com
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser & Version
      description: Which browser and version are you using?
      placeholder: e.g. Chrome 120, Brave 1.62
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you on?
      placeholder: e.g. macOS 14.2, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Conjure Version
      description: Which version of Conjure are you using? (check chrome://extensions)
      placeholder: e.g. 1.1.0
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful.
      placeholder: "This started after I updated the extension..."
    validations:
      required: false

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you like to help fix this bug?
      options:
        - label: I'd like to work on fixing this issue (pending maintainer approval)
          required: false
