name: Feature Request
description: Suggest a new feature or improvement for Conjure
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your ideas help make Conjure better for everyone.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added or improved?
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: why-helpful
    attributes:
      label: Why would this be helpful?
      description: Explain the problem this solves or how it would benefit users.
      placeholder: "This would help because..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how to implement this, please share them.
      placeholder: "This could be implemented by..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've considered..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that might be helpful.
      placeholder: "For example, other extensions do this by..."
    validations:
      required: false

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you like to help implement this feature?
      options:
        - label: I'd like to work on implementing this feature (pending maintainer approval)
          required: false